apiVersion: apps/v1
kind: Deployment
metadata:
  name: upstream
spec:
  selector:
    matchLabels:
      app: upstream
  replicas: 4
  template:
    metadata:
      labels:
        app: upstream
    spec:
      nodeSelector:
        tier: dummy-upstream-api-service
      containers:
        - name: upstream
          image: mangomm/go-bench-suite:latest
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1.5
          command: ["./go-bench-suite", "upstream"]
