prometheus:
  # scrapeInterval: "15s"
  # evaluationInterval: "30s"
  enableRemoteWriteReceiver: true
server:
  nodeSelector:
    tier: control-plane
alertmanager:
  nodeSelector:
    tier: control-plane