apiVersion: 1
datasources:
  - name: API Load Tests Prometheus
    type: prometheus
    url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 5s