{
 "title": "APIM performances",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "k6_rate_interval", "query": "10s" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "K6 metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "k6 iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iter/s" } },
   "targets": [
    {
     "expr": "rate(k6_iterations_total{ prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$k6_rate_interval])"
    }
   ]
  },
  {
   "title": "k6 virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vus" } },
   "targets": [
    {
     "expr": "k6_vus{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "current vus"
    }
   ]
  },
  {
   "title": "Failure trend",
   "type": "timeseries",
   "description": "Number of failure over time",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "k6_http_reqs_total{expected_response=\"false\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "k6 http throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$k6_rate_interval]))",
     "legendFormat": "Http {{status}}"
    }
   ]
  },
  {
   "title": "k6 bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(k6_data_sent_total{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$k6_rate_interval])"
    }
   ]
  },
  {
   "title": "k6 bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(k6_data_received_total{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$k6_rate_interval])"
    }
   ]
  },
  {
   "title": "k6 http duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(k6_http_req_duration_avg{ prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(k6_http_req_duration_p90{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "max(k6_http_req_duration_p95{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "max(k6_http_req_duration_p99{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway http throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gio_gw_http_server_requests_total{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]))",
     "legendFormat": "{{local}} ({{method}})"
    }
   ]
  },
  {
   "title": "Gateway active requests & connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "req." } },
   "targets": [
    {
     "expr": "gio_gw_http_server_active_requests{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "req. {{local}} ({{method}})"
    },
    {
     "expr": "gio_gw_http_server_active_connections{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "conn. {{local}}"
    }
   ]
  },
  {
   "title": "Gateway active backend requests & connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "req." } },
   "targets": [
    {
     "expr": "gio_gw_http_client_active_requests{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "req. {{remote}} ({{method}})"
    },
    {
     "expr": "gio_gw_http_client_active_connections{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "conn. {{remot}}"
    }
   ]
  },
  {
   "title": "Gateway backend throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(gio_gw_http_client_requests_total{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "{{remote}} ({{method}})"
    }
   ]
  },
  {
   "title": "Gateway http duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rate(gio_gw_http_server_response_time_seconds_sum{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) / rate(gio_gw_http_server_response_time_seconds_count{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) * 1000)",
     "legendFormat": "{{local}} ({{method}} - {{code}})"
    }
   ]
  },
  {
   "title": "Gateway http latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gio_gw_http_server_response_time_seconds_sum{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) / rate(gio_gw_http_server_response_time_seconds_count{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) * 1000",
     "legendFormat": "{{local}} ({{method}})"
    },
    {
     "expr": "rate(gio_gw_http_client_response_time_seconds_sum{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) / rate(gio_gw_http_client_response_time_seconds_count{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) * 1000",
     "legendFormat": "{{remote}} ({{method}})"
    }
   ]
  },
  {
   "title": "Gateway backend duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(gio_gw_http_client_response_time_seconds_sum{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) / rate(gio_gw_http_client_response_time_seconds_count{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]) * 1000",
     "legendFormat": "{{remote}} ({{method}})"
    }
   ]
  },
  {
   "title": "Gateway HTTP Client Queue avg time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gio_gw_http_client_queue_time_seconds_sum{application=\"gio-apim-gateway\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}/gio_gw_http_client_queue_time_seconds_count{application=\"gio-apim-gateway\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway HTTP Client Queue Pending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "gio_gw_http_client_queue_pending{application=\"gio-apim-gateway\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": " rate(gio_gw_http_server_request_bytes_sum{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "received from {{local}}"
    }
   ]
  },
  {
   "title": "Total received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_gw_http_server_bytes_read_total{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "received from {{local}}"
    }
   ]
  },
  {
   "title": "Gateway bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(rate(gio_gw_http_server_response_bytes_sum{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]))",
     "legendFormat": "sent to {{local}}"
    }
   ]
  },
  {
   "title": "Total sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_gw_http_server_bytes_written_total{application=\"gio-apim-gateway\", local=\"0.0.0.0:8082\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "sent to {{local}}"
    }
   ]
  },
  {
   "title": "Gateway backend bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(remote) (rate(gio_gw_http_client_request_bytes_sum{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]))",
     "legendFormat": "sent to {{remote}}"
    }
   ]
  },
  {
   "title": "Total sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_gw_http_client_bytes_written_total{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "sent to {{remote}}"
    }
   ]
  },
  {
   "title": "Gateway backend bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(remote) (rate(gio_gw_http_client_response_bytes_sum{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval]))",
     "legendFormat": "received from {{remote}}"
    }
   ]
  },
  {
   "title": "Total received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gio_gw_http_client_bytes_read_total{application=\"gio-apim-gateway\", remote!=\"localhost:9200\", cluster=\"$cluster\",prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "received from {{remote}}"
    }
   ]
  },
  {
   "title": "Gateway JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway jvm cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gio_gw_process_cpu_usage{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Gateway system cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gio_gw_system_cpu_usage{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "system cpu"
    }
   ]
  },
  {
   "title": "Gateway system load average 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "current cpu load"
    },
    {
     "expr": "gio_gw_system_cpu_count{prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "max cpu load"
    }
   ]
  },
  {
   "title": "Gateway heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gio_gw_jvm_memory_used_bytes{application=\"gio-apim-gateway\", area=\"heap\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "current heap"
    },
    {
     "expr": "sum(gio_gw_jvm_memory_max_bytes{application=\"gio-apim-gateway\", area=\"heap\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "max heap"
    }
   ]
  },
  {
   "title": "Gateway jvm memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gio_gw_jvm_memory_used_bytes{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Gateway jvm gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gio_gw_jvm_gc_pause_seconds_sum{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"}[$__rate_interval])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Gateway jvm total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(gio_gw_jvm_memory_used_bytes{application=\"gio-apim-gateway\", cluster=\"$cluster\", prometheus!=\"monitoring/prometheus-kube-prometheus-prometheus\"})",
     "legendFormat": "Total memory"
    }
   ]
  }
 ]
}