# MongoDB Database to store the configuration
# Skip if you plan to use only the Gravitee.io Kubernetes Operator
mongodb:
  enabled: true
  architecture: standalone
  nodeSelector:
    tier: control-plane

mongo:
  uri: mongodb://graviteeio-apim-mongodb-replicaset.gio-apim.svc.cluster.local:27017/gravitee

# Gravitee.io API Management Gateway
gateway:
  image:
    repository: graviteeio/apim-gateway
    tag: 4.3.2
  autoscaling:
    enabled: false
  replicaCount: 1
  deployment:
    nodeSelector:
      tier: gio-apim-gateway
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 3.5
      memory: 4Gi
  env:
    - name: GIO_MIN_MEM
      value: 512m
    - name: GIO_MAX_MEM
      value: 512m
    - name: JAVA_OPTS
      value: "-XX:MaxMetaspaceSize=256m -XX:CompressedClassSpaceSize=48m -XX:ReservedCodeCacheSize=32m -XX:+UseStringDeduplication -XX:MaxTenuringThreshold=1 -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=25 -Xss256k"
    - name: gravitee_http_instances
      value: "6"
  services:
    core:
      http:
        port: 18082
      service:
        enabled: true
        type: ClusterIP
        externalPort: 92
        appProtocol: http
    metrics:
      enabled: true
      prometheus:
        enabled: true
  ingress:
    enabled: false
  # DB-LESS mode if you plan to use only the Gravitee.io Kubernetes Operator
  # services:
  #   sync:
  #     kubernetes:
  #       enabled: true
  # dbLess: true
  reporters:
    elasticsearch:
      enabled: false

# Gravitee.io API Management API
# Skip if you plan to use only the Gravitee.io Kubernetes Operator
api:
  image:
    repository: graviteeio/apim-management-api
    tag: 4.3.2
  autoscaling:
    enabled: false
  replicaCount: 1
  deployment:
    nodeSelector:
      tier: control-plane
  analytics:
    type: none
  ingress:
    enabled: false

# Disable unnecessary components

portal:
  enabled: false

ui:
  enabled: false

es:
  enabled: false

ratelimit:
  type: none