apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: passthrough-v1
spec:
  name: "Passthrough"
  version: "1.0"
  description: "Passthrough API"
  plans:
    - name: "Open"
      description: "Open Keyless Plan"
      security: "KEY_LESS"
  proxy:
    virtual_hosts:
      - path: "/passthrough"
    groups:
      - endpoints:
          - name: "Default"
            target: "http://upstream.dummy-upstream-api-service.svc.cluster.local:8000"
  local: true