# As we only need the Gateway for performance testing, we run it in dbless mode.
gateway:
  image:
    repository: graviteeio/apim-gateway
    tag: 4.2.4
    pullPolicy: Always
  replicaCount: 1
  deployment:
    nodeSelector:
      tier: gio-apim-gateway
  autoscaling:
    enabled: false
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1
      memory: 256Mi
  ingress:
    enabled: true
    hosts:
      - localhost
  services:
    sync:
      kubernetes:
        enabled: true
  dbLess: true
  reporters:
    elasticsearch:
      enabled: false

# Disable unsed components

api:
  enabled: false

portal:
  enabled: false

ui:
  enabled: false

es:
  enabled: false

ratelimit:
  type: none